version: "3.9"
services:
  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    container_name: chrome
    ports:
      - "4444:4444"

  firefox:
    image: selenium/standalone-firefox
    hostname: firefox
    container_name: firefox
    ports:
      - "4445:4444"

  qa-framework:
    image: test-image:latest


